title: 블로그, 재테크 블로그
name: Your New Jekyll Site
highlighter: rouge

redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
      - with_toc_data

paginate: 10
